// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Author struct {
	Name        string         `json:"name"`
	Website     sql.NullString `json:"website"`
	Instagram   sql.NullString `json:"instagram"`
	Youtube     sql.NullString `json:"youtube"`
	UserCreated string         `json:"user_created"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Recipe struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Link         sql.NullString `json:"link"`
	AuthorName   string         `json:"author_name"`
	PrepTime     float64        `json:"prep_time"`
	PrepTimeUnit string         `json:"prep_time_unit"`
	UserCreated  string         `json:"user_created"`
	CreatedAt    time.Time      `json:"created_at"`
}

type RecipeIngredient struct {
	Name string `json:"name"`
	Unit string `json:"unit"`
	// cannot be negative
	Amount    float64   `json:"amount"`
	RecipeID  int64     `json:"recipe_id"`
	CreatedAt time.Time `json:"created_at"`
}

type RecipeStep struct {
	ID          int64     `json:"id"`
	Description string    `json:"description"`
	RecipeID    int64     `json:"recipe_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
